### ISSUE TITLE
Bug: Search capacity don't work

### ISSUE THREAD

**Issue by davi19** [davi19/storage_capacity#3]
The search of capacity don't work

1. Call searchCapacity with a phone 128 gb
2. the return 64GB

**Expected behavior**
The expected is the result 128 gb

**Desktop (please complete the following information):**
 - OS: IOS

**Smartphone (please complete the following information):**
 - Device: Iphone SE 2 Emulation

**Comment by davi19** [comment]
done

**Comment by JSBmanD** [comment]
@davi19 what the difference between search capacity and total space?
